
; These flashcards are from purelyfunctional.tv 

{:name       "Clojure Top 100"
 :image-file "clojure.png"
 :type "text"
 :grouping (fn [card cards] (if (= 1 (count (first card))) "oper" "func"))
 :cards

             [
"defn" "Define a function at the top level."
"let" "Bind names in a local scope."
"=" "Return true if all arguments are equal, false otherwise."
"is" "Assert that an expression returns truthy inside of a test."
"if" "Two-way conditional branch."
"fn" "Create a function."
"def" "Define a top level Var."
"str" "Convert the arguments to strings and concatenate them."
"deftest" "Define a test."
"map" "Create a seq whose elements are the result of applying a function to the elements of another seq."
"ns" "Define a namespace at the top of a file."
"->" "Thread-first macro."
"defn-" "Define a function at the top level that is private to the namespace."
"first" "Return the initial element of a seq."
"when" "One-way conditional branch."
"testing" "Add context text to enclosed assertions."
"or" "Evaluate expressions in turn, returning the first that is truthy or nil otherwise."
"apply" "Call a function on a seq of arguments."
"assoc" "Add one or more key/value pairs to an associative data structure such as a hashmap or vector."
"count" "Return the number of elements in the given collection."
"and" "Evaluate expressions in turn, returning the first that is not truthy, or the last one otherwise."
"not" "Return true if the argument is falsey, false otherwise."
"nil?" "Return true if the argument is nil, false otherwise."
"defmethod" "Define a method in a multimethod."
"+" "Add all arguments numerically."
"defmacro" "Define a new macro."
"get" "Return the value associated with the key in an associative data structure."
"*" "Multiply all arguments numerically."
"cond" "Multi-way conditional branch."
"recur" "Explicit tail recursion."
"println" "Print out all arguments and output a new line."
"do" "Execute all expressions and return the value of the last expression."
"seq" "Convert a value to a seq or nil if it's empty."
"doseq" "Iterate over a seq, executing the body expressions for each element."
"->>" "Thread last macro."
"throw" "Raise an exception."
"atom" "Create a Atom."
"reduce" "Starting with an initial value, apply a function to that value and successive elements of a seq."
"-" "Subtract arguments numerically, or negate a number."
"name" "Return the non-namespace part of a keyword or symbol as a string, or the argument itself if it's a string."
"instance?" "Check if a value is an instance of a class or interface."
"conj" "Add an element to a collection."
"if-let" "Two-way conditional branch with binding of the test result."
"inc" "Add one to a number."
"swap!" "Replace an Atom's value with the result of applying a function to the current value."
"into" "Add elements of a seq to a collection."
"range" "Create a seq of numbers from start to end."
"filter" "Keep elements of a seq that are truthy for a given predicate."
"get-in" "Get the value from a nested associative data structure at a path."
"merge" "Add key/value pairs from one map into another."
"empty?" "Returns true if there are no elements in a collection, false otherwise."
"loop" "Create a scope for tail recursion."
"for" "List comprehension."
"try" "Create a point for catching exception."
"list" "Create a list."
"format" "Create a string using java.lang.String.format."
"catch" "Declare what to do when a particular class of exception is caught."
"when-not" "Negative one-way conditional branch."
"rest" "Return a seq of elements from a collection excluding the first."
"<" "Mathematical less than."
"vec" "Convert a collection to a vector."
"partial" "Take a function and arguments and make a new function that has those arguments already applied."
"concat" "String seqs together in order."
"reset!" "Set the value of an Atom without regard to the current value."
"set" "Convert a collection to a set."
"when-let" "One-way conditional branch with binding of the test result."
"/" "Numeric division."
"int" "Convert a number to an integer."
"cons" "Add an element to the beginning of a seq."
"nth" "Retrieve an element from a seq by numeric index."
"assert" "Throw an AssertionError if expression is false."
"defproject" "Define a Leiningen project."
"second" "Return the second element of a seq."
"are" "Assert that multiple expressions are truthy in a test."
"contains?" "Does a key appear in an associative data structure?"
"update-in" "Modify a value at a path in a nested data structure by applying a function to that value."
">" "Mathematical greater than."
"doto" "Execute forms on first argument, then return it."
"defprotocol" "Define a new protocol."
"." "Execute a Java method."
"meta" "Return the metadata on a value."
"==" "Numeric equality comparison (type-independent)."
"keys" "Return a seq of keys from a hash map."
"next" "Return a seq of elements from a collection excluding the first, or nil if it's empty."
"map?" "Return true if the argument is a map, false otherwise."
"string?" "Return true if the argument is a string, false otherwise."
"set!" "Set thread-local vars, Java object instance fields, and Java class static fields."
"aget" "Return the value of an array at an index."
"keyword" "Create a keyword from a string or a namespace and name."
"if-not" "Two-way negative conditional branch."
"symbol" "Create a symbol from a string or a namespace and name."
"binding" "Create thread-local bindings for dynamic vars."
"dec" "Subtract one from a number."
"dissoc" "Remove a key/value from an associative data structure."
"defrecord" "Create a new record type."
"comp" "Compose two or more functions."
"not=" "Return true if the arguments are not equal, false otherwise."
"thrown?" "A special form in clojure.test/is expressions to check if an exception is thrown."
"float" "Convert a number to a Java float."
"select" "Return a new set keeping only elements that are truthy for a given predicate"
              ]
 }
